algorithm = "sha256"
version = "0.1.1"

[data]
"aa.toml" = '''
[token_configs]
[token_configs.coco_as]
url = 'https://trustee1.iudx.io:8080'

[token_configs.kbs]
url = 'https://trustee1.iudx.io:8080'
cert = """
-----BEGIN CERTIFICATE-----
MIIDtDCCApygAwIBAgIUVCgg0qruAgipPQmiUIzcaMxnjV4wDQYJKoZIhvcNAQEL
BQAwdDELMAkGA1UEBhMCVUsxEDAOBgNVBAgMB0VuZ2xhbmQxEDAOBgNVBAcMB0Jy
aXN0b2wxEDAOBgNVBAoMB1JlZCBIYXQxFDASBgNVBAsMC0RldmVsb3BtZW50MRkw
FwYDVQQDDBB0cnVzdGVlMS5pdWR4LmlvMB4XDTI1MDUxNDA2MTE0N1oXDTI2MDUx
NDA2MTE0N1owdDELMAkGA1UEBhMCVUsxEDAOBgNVBAgMB0VuZ2xhbmQxEDAOBgNV
BAcMB0JyaXN0b2wxEDAOBgNVBAoMB1JlZCBIYXQxFDASBgNVBAsMC0RldmVsb3Bt
ZW50MRkwFwYDVQQDDBB0cnVzdGVlMS5pdWR4LmlvMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAtDqb7AcsCnUMSy6JQYyiSgiZwlJsTFQdx0rvGlyIhdt6
d1WwHHsytIoHFR3v/ME62FLY775V7QT1UM4X4iKe7wTkK4nahSvrYvKKi43IVHrq
ksFiHFU/UrwYI2ZnvaBCWfquJHTBPnuhjsh0tV689E+5Q8dvhOGBBJ2sQE4UQc9u
hx4FKid3qIo9kRlxVD3ni3029YVfXr+I+sW6jWOh1548ipjegmkaAtu7IQi+f+XR
lUn6BIH3YSVfEihKLSY41EDwlMNNFvaETbgF7DN5ipJ+p6H+M66JuwID6No086QO
/ALZrWQHPKka1aSzAZ2iSyWyYdVPT283x3+pRwKY8wIDAQABoz4wPDAbBgNVHREE
FDASghB0cnVzdGVlMS5pdWR4LmlvMB0GA1UdDgQWBBSLOYnK7DYOuzShDNTs3bLs
Jt/WSzANBgkqhkiG9w0BAQsFAAOCAQEABTkmE/4L7blDkhu79F0xbBUzGzA4S1mz
VF0uNG1XDBjzElL5prQQuKRxSEN5nDyO93UTEGMQ2uPlUy6SlmOfxvKYc/djrbSt
4DtPtadbJkV6QIRm6x9C/47rGlTdV+Fo7OkJaG6iMG232WwKDlu4MQb29S64fbkR
dWXccVl1DftA/hEgIbs2a4CmbH+X3U+rsvKkbx3jnL7rihicDN/UkGLP4zgb/iTB
h551iYk/M0PQ6Ylzvdaf7tRAVqJXYt+edIWBkmXJZcywhmWI+LzVklle5Dku7trN
wzqZN7n074mXtsX74Kdv7twoF9NnvE5OGUQwkbjsFl62qCjlImVbEA==
-----END CERTIFICATE-----
"""
'''

"cdh.toml"  = '''
socket = 'unix:///run/confidential-containers/cdh.sock'

[kbc]
name = 'cc_kbc'
url = 'https://trustee2.iudx.io:8080'
kbs_cert = """
-----BEGIN CERTIFICATE-----
MIIDtDCCApygAwIBAgIUTvsP95g9vBqfis9LASPN6C5YXwUwDQYJKoZIhvcNAQEL
BQAwdDELMAkGA1UEBhMCVUsxEDAOBgNVBAgMB0VuZ2xhbmQxEDAOBgNVBAcMB0Jy
aXN0b2wxEDAOBgNVBAoMB1JlZCBIYXQxFDASBgNVBAsMC0RldmVsb3BtZW50MRkw
FwYDVQQDDBB0cnVzdGVlMi5pdWR4LmlvMB4XDTI1MDUxNDA2MTQyMloXDTI2MDUx
NDA2MTQyMlowdDELMAkGA1UEBhMCVUsxEDAOBgNVBAgMB0VuZ2xhbmQxEDAOBgNV
BAcMB0JyaXN0b2wxEDAOBgNVBAoMB1JlZCBIYXQxFDASBgNVBAsMC0RldmVsb3Bt
ZW50MRkwFwYDVQQDDBB0cnVzdGVlMi5pdWR4LmlvMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAqeuW6fzPIIy15hHvQ9QG7nC6hrZiMq/a9wIHgtNTxWRs
PSV5aMpE4eHxnkxSqX2HQngKfapl/xW9dPFzfav9T9ZedKxub7mWkMARWf2ISOr8
vz9rSkjt61Vseo7gXHVAlFvjWvbDlMcfRnkG5cMZDqm+XJqCPA54vYLYMYBlfFvX
weAGC+NAMmYUVAAp647SZkip6iLMjzlKG9EGoCkbnO7crN5+79OZ2LgHfJicd63+
kBLzW4vYTmb7A4/2tYLDGzIHK4wfXa6TNVjaykGViPBkNTXGcAKl9303AhL7KdhT
THe8/X5vQvonsjySTTeMZVYHq4drauNyGI38OROmGQIDAQABoz4wPDAbBgNVHREE
FDASghB0cnVzdGVlMi5pdWR4LmlvMB0GA1UdDgQWBBQ8bJb+Vb1eCFANK5lOfdlj
SRDr/DANBgkqhkiG9w0BAQsFAAOCAQEAnjJW9cgAPCxDfUkaCznxRD48NgYZRt4c
pwcN2P7C4oiNgK4XF65m2DnB2BvKsCgsEr+y7vPftoQeTP3OUHnsUPxJxlswqciT
7Y89fHTZBt2AZGhFwCEBPb2x0E7JSS6ffDy4fObHElAGOwl1dPFz6ff4mdALnDFC
0+xt3uf3AfLVYwpO8MSzGhHmbW72kuc1NDdlNA0fhuhTUbQK1FxmuYyAU629B8wX
EW056qpARF6Y6wimAO7Jx5PmFl9qNuIOwLgXlpJZuQzI8W+6mShhk/xNNDP0mEZK
OlMpYLsb3b6Y2I36JaSXFaOSO8vd8pUgNJ0rO4jfajsDPeUQqES1Rw==
-----END CERTIFICATE-----
"""
'''